swagger: '2.0'
info:
  title: Qlab Racetrack
  description: Qlab competition thingy
  version: 1.0.0
host: api.qlabsomething.com
schemes:
  - http
basePath: /v2
produces:
  - application/json
paths:
  /currentProblem:
    get:
      summary: Problem Description
      description: |
        Race to respond to my clue
      responses:
        '200':
          description: Problem string
          schema:
            $ref: '#/definitions/Problem'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /submitAnswer:
    get:
      summary: stuff
      description: |
         more stuff
      parameters:
        - name: answer
          in: query
          description: Answer submission
          required: true
          type: string
          format: string
      responses:
        '200':
          description: Right or wrong
          schema:
            type: boolean
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Problem:
    type: object
    properties:
      repeat_string:
        type: string
        description: 'submit this string as an answer'
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
